In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
df= pd.read_pickle("final_train_test_risk_score.pkl.bz2",compression="bz2")

In [4]:
df.head().T

0                 1            2  \
defaul_payment_hist                    0                 0            0   
credit_history                     10957              5114         4595   
open_acc                               3                 3            2   
indebtedness                           0                 0            0   
member_id                         786442            655371       917517   
amount                            180957            151353        98831   
mf_return                    1.90006e+07       6.16484e+06  6.68061e+06   
balance                           260478            221916       143652   
score                            267.434           168.518      169.171   
improvement             investment_score  investment_score   risk_score   
cumulative_tenure                    213               208           90   
cumulative_inv_amount            2576727           1950971       973186   
cumulative_risk                       48                17            0   
total_mfs                             16                17            9   
total_tenure                         123               136           80   
mf_cat_equity_scheme                   2                 1            0   
mf_cat_debt_scheme                     2                 4            3   
mf_cat_other_scheme                    0                 0            1   
mf_cat_hybrid_scheme                   0                 0            0   
mf_cat_solution_scheme                 0                 0            1   
mf_cat_others                         12                10            4   

                                       3            4  
defaul_payment_hist                   35           38  
credit_history                      6909         7426  
open_acc                              10           15  
indebtedness                           0      17.4687  
member_id                         786448       917526  
amount                            174366        80588  
mf_return                    1.20015e+07  5.84016e+06  
balance                           254640       113281  
score                            201.577      265.713  
improvement             investment_score    roi_score  
cumulative_tenure                    179           87  
cumulative_inv_amount            2059523      1214105  
cumulative_risk                       15           30  
total_mfs                             15            6  
total_tenure                          92           68  
mf_cat_equity_scheme                   0            0  
mf_cat_debt_scheme                     3            1  
mf_cat_other_scheme                    0            0  
mf_cat_hybrid_scheme                   0            0  
mf_cat_solution_scheme                 0            0  
mf_cat_others                          9            5

In [5]:
df.drop(["score","member_id"],axis=1,inplace=True)

In [6]:
df.head().T

0                 1            2  \
defaul_payment_hist                    0                 0            0   
credit_history                     10957              5114         4595   
open_acc                               3                 3            2   
indebtedness                           0                 0            0   
amount                            180957            151353        98831   
mf_return                    1.90006e+07       6.16484e+06  6.68061e+06   
balance                           260478            221916       143652   
improvement             investment_score  investment_score   risk_score   
cumulative_tenure                    213               208           90   
cumulative_inv_amount            2576727           1950971       973186   
cumulative_risk                       48                17            0   
total_mfs                             16                17            9   
total_tenure                         123               136           80   
mf_cat_equity_scheme                   2                 1            0   
mf_cat_debt_scheme                     2                 4            3   
mf_cat_other_scheme                    0                 0            1   
mf_cat_hybrid_scheme                   0                 0            0   
mf_cat_solution_scheme                 0                 0            1   
mf_cat_others                         12                10            4   

                                       3            4  
defaul_payment_hist                   35           38  
credit_history                      6909         7426  
open_acc                              10           15  
indebtedness                           0      17.4687  
amount                            174366        80588  
mf_return                    1.20015e+07  5.84016e+06  
balance                           254640       113281  
improvement             investment_score    roi_score  
cumulative_tenure                    179           87  
cumulative_inv_amount            2059523      1214105  
cumulative_risk                       15           30  
total_mfs                             15            6  
total_tenure                          92           68  
mf_cat_equity_scheme                   0            0  
mf_cat_debt_scheme                     3            1  
mf_cat_other_scheme                    0            0  
mf_cat_hybrid_scheme                   0            0  
mf_cat_solution_scheme                 0            0  
mf_cat_others                          9            5

In [7]:
improvements=df["improvement"].nunique()
improvements

7

In [8]:
X=df.drop(columns="improvement",axis=1)
y=df["improvement"]

In [8]:
y = df["improvement"].astype("category").cat.codes

In [5]:
improvement_list=df["improvement"].value_counts().index.to_list()

In [70]:
df["improvement"].value_counts()

risk_score          13295
roi_score           11341
investment_score     7432
credit_score         2840
time_score           2527
diversity_score       146
confidence_score      112
Name: improvement, dtype: int64

In [6]:
df_improvements=pd.DataFrame()

In [7]:
df_improvements["improvement"]=improvement_list

In [9]:
df_improvements["index"]=y.value_counts().index.to_list()

In [71]:
y.value_counts()

4    13295
5    11341
3     7432
1     2840
6     2527
2      146
0      112
dtype: int64

In [11]:
df_improvements.to_pickle("improvement_mapping.pkl")

In [58]:
y.value_counts().index

Int64Index([4, 5, 3, 1, 6, 2, 0], dtype='int64')

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [14]:
# Test ,Train split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7,test_size=0.3,random_state=100)

In [15]:
X_train = scaler.fit_transform(X_train)

In [18]:
input_shape=X_train.shape
input_shape


(26385, 18)

In [17]:
output_shape=y_train.shape
output_shape

(26385,)

In [19]:
def one_hot(j,output):
    # input is the target dataset of shape (1, m) where m is the number of data points
    # returns a 2 dimensional array of shape (10, m) where each target value is converted to a one hot encoding
    # Look at the next block of code for a better understanding of one hot encoding
    n = j.shape[0]
    new_array = np.zeros((output, n))
    index = 0
    for res in j:
        new_array[res][index] = 1.0
        index = index + 1
    return new_array

In [22]:
y_train_enc=one_hot(y_train,improvements)
y_train_enc

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 1., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
y_train_enc.shape

(7, 26385)

In [24]:
y_train =y_train_enc.T

In [25]:
X_train.shape

(26385, 18)

In [37]:
input_shape=X_train.shape[1]
input_shape

18

In [26]:
output=y_train.shape[1]
output

7

In [27]:
y_train.shape

(26385, 7)

In [30]:
#!pip install -q keras

In [29]:
from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Activation ,Flatten
from tensorflow.keras import regularizers

In [38]:
# create model
nn_model = Sequential()
nn_model.add(Dense(128, input_dim=input_shape, activation='relu'))
nn_model.add(Dropout(rate=0.3))
nn_model.add(BatchNormalization())
nn_model.add(Dense(64, activation = 'relu'))
nn_model.add(Dropout(rate=0.3))
nn_model.add(BatchNormalization())
nn_model.add(Dense(32, activation = 'relu'))
nn_model.add(Dense(output, activation='softmax'))

In [40]:
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 128)               2432      
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 128)               512       
_________________________________________________________________
dense_5 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_3 (Dropout)          (None, 64)                0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 64)                256       
_________________________________________________________________
dense_6 (Dense)              (None, 32)               

In [41]:
nn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

In [43]:
nn_model.fit(X_train, y_train, epochs=50, batch_size=100)

Train on 26385 samples
Epoch 1/50
26385/26385 [==============================] - 2s 63us/sample - loss: 0.3143 - acc: 0.8835
Epoch 2/50
26385/26385 [==============================] - 2s 63us/sample - loss: 0.3003 - acc: 0.8888
Epoch 3/50
26385/26385 [==============================] - 2s 61us/sample - loss: 0.3006 - acc: 0.8896
Epoch 4/50
26385/26385 [==============================] - 2s 62us/sample - loss: 0.2965 - acc: 0.8902
Epoch 5/50
26385/26385 [==============================] - 2s 64us/sample - loss: 0.2918 - acc: 0.8936
Epoch 6/50
26385/26385 [==============================] - 2s 62us/sample - loss: 0.2896 - acc: 0.8920
Epoch 7/50
26385/26385 [==============================] - 2s 63us/sample - loss: 0.2841 - acc: 0.8964
Epoch 8/50
26385/26385 [==============================] - 2s 62us/sample - loss: 0.2818 - acc: 0.8963
Epoch 9/50
26385/26385 [==============================] - 2s 62us/sample - loss: 0.2844 - acc: 0.8958
Epoch 10/50
26385/26385 [==============================] - 

In [44]:
scores_train = nn_model.evaluate(X_train, y_train)
print("\n%s: %.2f%%" % (nn_model.metrics_names[1], scores_train[1]*100))

26385/26385 [==============================] - 2s 72us/sample - loss: 0.1332 - acc: 0.9539

acc: 95.39%


In [46]:
X_test = scaler.fit_transform(X_test)

In [47]:
y_test_enc=one_hot(y_test,improvements)
y_test_enc

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [48]:
y_test=y_test_enc.T

In [49]:
scores_train = nn_model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (nn_model.metrics_names[1], scores_train[1]*100))

11308/11308 [==============================] - 1s 63us/sample - loss: 0.1752 - acc: 0.9315

acc: 93.15%


In [50]:
test=X_test[:1]

In [80]:
test

array([[0.37391304, 0.22091054, 0.10810811, 0.        , 0.12887439,
        0.09684344, 0.12920137, 0.12635379, 0.08593061, 0.12631579,
        0.16666667, 0.20588235, 0.14285714, 0.16666667, 0.        ,
        0.        , 0.        , 0.05882353]])

In [52]:
predictions = nn_model.predict(test)
predictions

array([[1.5919998e-03, 1.1137313e-04, 9.2452821e-05, 2.4858431e-05,
        5.2024162e-01, 4.5161945e-04, 4.7748610e-01]], dtype=float32)

In [53]:
nn_model.save("improvement_nn_model.h5")

In [72]:
top_2=(-predictions.ravel()).argsort()[:2]

In [73]:
top_2

array([4, 6])

In [ ]:
df_improvements

In [78]:
df_improvements[(df_improvements["index"].isin(top_2))]["improvement"].to_list()

['risk_score', 'time_score']

In [19]:
improve={"diversity_score":["Diversify your mutual funds. Don't invest only in one type of funds"],
         "roi_score":["Your overall mutual fund rate of return is low. Try to invest in high return funds"],
         "risk_score": ["Diversify your risk. Most of the funds are under same risk."],
        "investment_score":["You can have funds available for investments. It's a good practice to invest 10-15% of your funds"],
         "time_score": ["Its good to invest the mutual funds for a longer period to get the power of compound interest"],
         "credit_score": ["Try to avoid defaulting on your loan installments. Its impacts your financial score like CIBIL and future loan applications."],
         "confidence_score":["Try to invest for more time and more funds, to get higher returns using the power of compound interest"]
        }

In [99]:
type(improve)

dict

In [20]:
improvement_dict=pd.DataFrame(improve).T.reset_index()

In [21]:
improvement_dict.columns=["improvement","text"]

In [110]:
improvement_dict[improvement_dict["improvement"].isin(['risk_score', 'time_score'])]["text"].to_list()

['Diversify your risk. Most of the funds are under same risk.',
 'Its good to invest the mutual funds for a longer period to get the power of compound interest']

In [24]:
improvement_dict.to_dict(orient='records')

[{'improvement': 'diversity_score',
  'text': "Diversify your mutual funds. Don't invest only in one type of funds"},
 {'improvement': 'roi_score',
  'text': 'Your overall mutual fund rate of return is low. Try to invest in high return funds'},
 {'improvement': 'risk_score',
  'text': 'Diversify your risk. Most of the funds are under same risk.'},
 {'improvement': 'investment_score',
  'text': "You can have funds available for investments. It's a good practice to invest 10-15% of your funds"},
 {'improvement': 'time_score',
  'text': 'Its good to invest the mutual funds for a longer period to get the power of compound interest'},
 {'improvement': 'credit_score',
  'text': 'Try to avoid defaulting on your loan installments. Its impacts your financial score like CIBIL and future loan applications.'},
 {'improvement': 'confidence_score',
  'text': 'Try to invest for more time and more funds, to get higher returns using the power of compound interest'}]